// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

public interface ClientContextProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autofill_assistant.ClientContextProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .autofill_assistant.ClientContextProto.Chrome chrome = 1;</code>
   */
  boolean hasChrome();
  /**
   * <code>optional .autofill_assistant.ClientContextProto.Chrome chrome = 1;</code>
   */
  org.chromium.chrome.browser.autofill_assistant.proto.ClientContextProto.Chrome getChrome();

  /**
   * <pre>
   * locale will be the language tag of the default locale. The tag should
   * be a well-formed IETF BCP 47 language tag with language and country code
   * (e.g., "en-US").
   * The intent is to communicate the client language preferences to the server.
   * </pre>
   *
   * <code>optional string locale = 5;</code>
   */
  boolean hasLocale();
  /**
   * <pre>
   * locale will be the language tag of the default locale. The tag should
   * be a well-formed IETF BCP 47 language tag with language and country code
   * (e.g., "en-US").
   * The intent is to communicate the client language preferences to the server.
   * </pre>
   *
   * <code>optional string locale = 5;</code>
   */
  java.lang.String getLocale();
  /**
   * <pre>
   * locale will be the language tag of the default locale. The tag should
   * be a well-formed IETF BCP 47 language tag with language and country code
   * (e.g., "en-US").
   * The intent is to communicate the client language preferences to the server.
   * </pre>
   *
   * <code>optional string locale = 5;</code>
   */
  com.google.protobuf.ByteString
      getLocaleBytes();

  /**
   * <pre>
   * country should be a country code as defined by ISO 3166-1-alpha-2.
   * The intent is to communicate the client's location to the server.
   * </pre>
   *
   * <code>optional string country = 6;</code>
   */
  boolean hasCountry();
  /**
   * <pre>
   * country should be a country code as defined by ISO 3166-1-alpha-2.
   * The intent is to communicate the client's location to the server.
   * </pre>
   *
   * <code>optional string country = 6;</code>
   */
  java.lang.String getCountry();
  /**
   * <pre>
   * country should be a country code as defined by ISO 3166-1-alpha-2.
   * The intent is to communicate the client's location to the server.
   * </pre>
   *
   * <code>optional string country = 6;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <pre>
   * Experiment ids string provided by the 'caller'.
   * </pre>
   *
   * <code>optional string experiment_ids = 7;</code>
   */
  boolean hasExperimentIds();
  /**
   * <pre>
   * Experiment ids string provided by the 'caller'.
   * </pre>
   *
   * <code>optional string experiment_ids = 7;</code>
   */
  java.lang.String getExperimentIds();
  /**
   * <pre>
   * Experiment ids string provided by the 'caller'.
   * </pre>
   *
   * <code>optional string experiment_ids = 7;</code>
   */
  com.google.protobuf.ByteString
      getExperimentIdsBytes();

  /**
   * <pre>
   * True if the script is called from a Chrome Custom Tab created for Autofill
   * Assistant.
   * </pre>
   *
   * <code>optional bool is_cct = 8;</code>
   */
  boolean hasIsCct();
  /**
   * <pre>
   * True if the script is called from a Chrome Custom Tab created for Autofill
   * Assistant.
   * </pre>
   *
   * <code>optional bool is_cct = 8;</code>
   */
  boolean getIsCct();

  /**
   * <pre>
   * True if the onboarding screen was shown to the user.
   * </pre>
   *
   * <code>optional bool is_onboarding_shown = 10;</code>
   */
  boolean hasIsOnboardingShown();
  /**
   * <pre>
   * True if the onboarding screen was shown to the user.
   * </pre>
   *
   * <code>optional bool is_onboarding_shown = 10;</code>
   */
  boolean getIsOnboardingShown();

  /**
   * <pre>
   * True if the script was triggered by a direct action.
   * </pre>
   *
   * <code>optional bool is_direct_action = 9;</code>
   */
  boolean hasIsDirectAction();
  /**
   * <pre>
   * True if the script was triggered by a direct action.
   * </pre>
   *
   * <code>optional bool is_direct_action = 9;</code>
   */
  boolean getIsDirectAction();

  /**
   * <code>optional .autofill_assistant.ClientContextProto.DeviceContextProto device_context = 11;</code>
   */
  boolean hasDeviceContext();
  /**
   * <code>optional .autofill_assistant.ClientContextProto.DeviceContextProto device_context = 11;</code>
   */
  org.chromium.chrome.browser.autofill_assistant.proto.ClientContextProto.DeviceContextProto getDeviceContext();

  public org.chromium.chrome.browser.autofill_assistant.proto.ClientContextProto.ClientCase getClientCase();
}
