// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

/**
 * <pre>
 * Contain all arguments to focus on an element.
 * </pre>
 *
 * Protobuf type {@code autofill_assistant.FocusElementProto}
 */
public  final class FocusElementProto extends
    com.google.protobuf.GeneratedMessageLite<
        FocusElementProto, FocusElementProto.Builder> implements
    // @@protoc_insertion_point(message_implements:autofill_assistant.FocusElementProto)
    FocusElementProtoOrBuilder {
  private FocusElementProto() {
    title_ = "";
    deprecatedTouchableElements_ = emptyProtobufList();
  }
  public interface TopPaddingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:autofill_assistant.FocusElementProto.TopPadding)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Padding in CSS pixels. Eg. 20.
     * </pre>
     *
     * <code>optional int32 pixels = 1;</code>
     */
    boolean hasPixels();
    /**
     * <pre>
     * Padding in CSS pixels. Eg. 20.
     * </pre>
     *
     * <code>optional int32 pixels = 1;</code>
     */
    int getPixels();

    /**
     * <pre>
     * Ratio in relation to the window.innerHeight. Eg. 0.25.
     * </pre>
     *
     * <code>optional float ratio = 2;</code>
     */
    boolean hasRatio();
    /**
     * <pre>
     * Ratio in relation to the window.innerHeight. Eg. 0.25.
     * </pre>
     *
     * <code>optional float ratio = 2;</code>
     */
    float getRatio();

    public org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.TopPaddingCase getTopPaddingCase();
  }
  /**
   * Protobuf type {@code autofill_assistant.FocusElementProto.TopPadding}
   */
  public  static final class TopPadding extends
      com.google.protobuf.GeneratedMessageLite<
          TopPadding, TopPadding.Builder> implements
      // @@protoc_insertion_point(message_implements:autofill_assistant.FocusElementProto.TopPadding)
      TopPaddingOrBuilder {
    private TopPadding() {
    }
    private int bitField0_;
    private int topPaddingCase_ = 0;
    private java.lang.Object topPadding_;
    public enum TopPaddingCase
        implements com.google.protobuf.Internal.EnumLite {
      PIXELS(1),
      RATIO(2),
      TOPPADDING_NOT_SET(0);
      private final int value;
      private TopPaddingCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TopPaddingCase valueOf(int value) {
        return forNumber(value);
      }

      public static TopPaddingCase forNumber(int value) {
        switch (value) {
          case 1: return PIXELS;
          case 2: return RATIO;
          case 0: return TOPPADDING_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TopPaddingCase
    getTopPaddingCase() {
      return TopPaddingCase.forNumber(
          topPaddingCase_);
    }

    private void clearTopPadding() {
      topPaddingCase_ = 0;
      topPadding_ = null;
    }

    public static final int PIXELS_FIELD_NUMBER = 1;
    /**
     * <pre>
     * Padding in CSS pixels. Eg. 20.
     * </pre>
     *
     * <code>optional int32 pixels = 1;</code>
     */
    public boolean hasPixels() {
      return topPaddingCase_ == 1;
    }
    /**
     * <pre>
     * Padding in CSS pixels. Eg. 20.
     * </pre>
     *
     * <code>optional int32 pixels = 1;</code>
     */
    public int getPixels() {
      if (topPaddingCase_ == 1) {
        return (java.lang.Integer) topPadding_;
      }
      return 0;
    }
    /**
     * <pre>
     * Padding in CSS pixels. Eg. 20.
     * </pre>
     *
     * <code>optional int32 pixels = 1;</code>
     */
    private void setPixels(int value) {
      topPaddingCase_ = 1;
      topPadding_ = value;
    }
    /**
     * <pre>
     * Padding in CSS pixels. Eg. 20.
     * </pre>
     *
     * <code>optional int32 pixels = 1;</code>
     */
    private void clearPixels() {
      if (topPaddingCase_ == 1) {
        topPaddingCase_ = 0;
        topPadding_ = null;
      }
    }

    public static final int RATIO_FIELD_NUMBER = 2;
    /**
     * <pre>
     * Ratio in relation to the window.innerHeight. Eg. 0.25.
     * </pre>
     *
     * <code>optional float ratio = 2;</code>
     */
    public boolean hasRatio() {
      return topPaddingCase_ == 2;
    }
    /**
     * <pre>
     * Ratio in relation to the window.innerHeight. Eg. 0.25.
     * </pre>
     *
     * <code>optional float ratio = 2;</code>
     */
    public float getRatio() {
      if (topPaddingCase_ == 2) {
        return (java.lang.Float) topPadding_;
      }
      return 0F;
    }
    /**
     * <pre>
     * Ratio in relation to the window.innerHeight. Eg. 0.25.
     * </pre>
     *
     * <code>optional float ratio = 2;</code>
     */
    private void setRatio(float value) {
      topPaddingCase_ = 2;
      topPadding_ = value;
    }
    /**
     * <pre>
     * Ratio in relation to the window.innerHeight. Eg. 0.25.
     * </pre>
     *
     * <code>optional float ratio = 2;</code>
     */
    private void clearRatio() {
      if (topPaddingCase_ == 2) {
        topPaddingCase_ = 0;
        topPadding_ = null;
      }
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (topPaddingCase_ == 1) {
        output.writeInt32(
            1, (int)((java.lang.Integer) topPadding_));
      }
      if (topPaddingCase_ == 2) {
        output.writeFloat(
            2, (float)((java.lang.Float) topPadding_));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (topPaddingCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              1, (int)((java.lang.Integer) topPadding_));
      }
      if (topPaddingCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(
              2, (float)((java.lang.Float) topPadding_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code autofill_assistant.FocusElementProto.TopPadding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding, Builder> implements
        // @@protoc_insertion_point(builder_implements:autofill_assistant.FocusElementProto.TopPadding)
        org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPaddingOrBuilder {
      // Construct using org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      public TopPaddingCase
          getTopPaddingCase() {
        return instance.getTopPaddingCase();
      }

      public Builder clearTopPadding() {
        copyOnWrite();
        instance.clearTopPadding();
        return this;
      }


      /**
       * <pre>
       * Padding in CSS pixels. Eg. 20.
       * </pre>
       *
       * <code>optional int32 pixels = 1;</code>
       */
      public boolean hasPixels() {
        return instance.hasPixels();
      }
      /**
       * <pre>
       * Padding in CSS pixels. Eg. 20.
       * </pre>
       *
       * <code>optional int32 pixels = 1;</code>
       */
      public int getPixels() {
        return instance.getPixels();
      }
      /**
       * <pre>
       * Padding in CSS pixels. Eg. 20.
       * </pre>
       *
       * <code>optional int32 pixels = 1;</code>
       */
      public Builder setPixels(int value) {
        copyOnWrite();
        instance.setPixels(value);
        return this;
      }
      /**
       * <pre>
       * Padding in CSS pixels. Eg. 20.
       * </pre>
       *
       * <code>optional int32 pixels = 1;</code>
       */
      public Builder clearPixels() {
        copyOnWrite();
        instance.clearPixels();
        return this;
      }

      /**
       * <pre>
       * Ratio in relation to the window.innerHeight. Eg. 0.25.
       * </pre>
       *
       * <code>optional float ratio = 2;</code>
       */
      public boolean hasRatio() {
        return instance.hasRatio();
      }
      /**
       * <pre>
       * Ratio in relation to the window.innerHeight. Eg. 0.25.
       * </pre>
       *
       * <code>optional float ratio = 2;</code>
       */
      public float getRatio() {
        return instance.getRatio();
      }
      /**
       * <pre>
       * Ratio in relation to the window.innerHeight. Eg. 0.25.
       * </pre>
       *
       * <code>optional float ratio = 2;</code>
       */
      public Builder setRatio(float value) {
        copyOnWrite();
        instance.setRatio(value);
        return this;
      }
      /**
       * <pre>
       * Ratio in relation to the window.innerHeight. Eg. 0.25.
       * </pre>
       *
       * <code>optional float ratio = 2;</code>
       */
      public Builder clearRatio() {
        copyOnWrite();
        instance.clearRatio();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:autofill_assistant.FocusElementProto.TopPadding)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding other = (org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding) arg1;
          switch (other.getTopPaddingCase()) {
            case PIXELS: {
              topPadding_ = visitor.visitOneofInt(
                  topPaddingCase_ == 1, topPadding_, other.topPadding_);
              break;
            }
            case RATIO: {
              topPadding_ = visitor.visitOneofFloat(
                  topPaddingCase_ == 2, topPadding_, other.topPadding_);
              break;
            }
            case TOPPADDING_NOT_SET: {
              visitor.visitOneofNotSet(topPaddingCase_ != 0);
              break;
            }
          }
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            if (other.topPaddingCase_ != 0) {
              topPaddingCase_ = other.topPaddingCase_;
            }
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  topPaddingCase_ = 1;
                  topPadding_ = input.readInt32();
                  break;
                }
                case 21: {
                  topPaddingCase_ = 2;
                  topPadding_ = input.readFloat();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:autofill_assistant.FocusElementProto.TopPadding)
    private static final org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TopPadding();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TopPadding> PARSER;

    public static com.google.protobuf.Parser<TopPadding> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  private int bitField0_;
  public static final int ELEMENT_FIELD_NUMBER = 1;
  private org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto element_;
  /**
   * <pre>
   * Element to focus on.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  public boolean hasElement() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * Element to focus on.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto getElement() {
    return element_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.getDefaultInstance() : element_;
  }
  /**
   * <pre>
   * Element to focus on.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  private void setElement(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
    if (value == null) {
      throw new NullPointerException();
    }
    element_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <pre>
   * Element to focus on.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  private void setElement(
      org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
    element_ = builderForValue.build();
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * Element to focus on.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  private void mergeElement(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
    if (element_ != null &&
        element_ != org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.getDefaultInstance()) {
      element_ =
        org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.newBuilder(element_).mergeFrom(value).buildPartial();
    } else {
      element_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * Element to focus on.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
   */
  private void clearElement() {  element_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private java.lang.String title_;
  /**
   * <pre>
   * Optional title to show in the status bar.
   * </pre>
   *
   * <code>optional string title = 2;</code>
   */
  public boolean hasTitle() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * Optional title to show in the status bar.
   * </pre>
   *
   * <code>optional string title = 2;</code>
   */
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <pre>
   * Optional title to show in the status bar.
   * </pre>
   *
   * <code>optional string title = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <pre>
   * Optional title to show in the status bar.
   * </pre>
   *
   * <code>optional string title = 2;</code>
   */
  private void setTitle(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    title_ = value;
  }
  /**
   * <pre>
   * Optional title to show in the status bar.
   * </pre>
   *
   * <code>optional string title = 2;</code>
   */
  private void clearTitle() {
    bitField0_ = (bitField0_ & ~0x00000002);
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <pre>
   * Optional title to show in the status bar.
   * </pre>
   *
   * <code>optional string title = 2;</code>
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    title_ = value.toStringUtf8();
  }

  public static final int DEPRECATED_TOUCHABLE_ELEMENTS_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto> deprecatedTouchableElements_;
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  public java.util.List<org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto> getDeprecatedTouchableElementsList() {
    return deprecatedTouchableElements_;
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  public java.util.List<? extends org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProtoOrBuilder> 
      getDeprecatedTouchableElementsOrBuilderList() {
    return deprecatedTouchableElements_;
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  public int getDeprecatedTouchableElementsCount() {
    return deprecatedTouchableElements_.size();
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto getDeprecatedTouchableElements(int index) {
    return deprecatedTouchableElements_.get(index);
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProtoOrBuilder getDeprecatedTouchableElementsOrBuilder(
      int index) {
    return deprecatedTouchableElements_.get(index);
  }
  private void ensureDeprecatedTouchableElementsIsMutable() {
    if (!deprecatedTouchableElements_.isModifiable()) {
      deprecatedTouchableElements_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(deprecatedTouchableElements_);
     }
  }

  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void setDeprecatedTouchableElements(
      int index, org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureDeprecatedTouchableElementsIsMutable();
    deprecatedTouchableElements_.set(index, value);
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void setDeprecatedTouchableElements(
      int index, org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
    ensureDeprecatedTouchableElementsIsMutable();
    deprecatedTouchableElements_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void addDeprecatedTouchableElements(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureDeprecatedTouchableElementsIsMutable();
    deprecatedTouchableElements_.add(value);
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void addDeprecatedTouchableElements(
      int index, org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureDeprecatedTouchableElementsIsMutable();
    deprecatedTouchableElements_.add(index, value);
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void addDeprecatedTouchableElements(
      org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
    ensureDeprecatedTouchableElementsIsMutable();
    deprecatedTouchableElements_.add(builderForValue.build());
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void addDeprecatedTouchableElements(
      int index, org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
    ensureDeprecatedTouchableElementsIsMutable();
    deprecatedTouchableElements_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void addAllDeprecatedTouchableElements(
      java.lang.Iterable<? extends org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto> values) {
    ensureDeprecatedTouchableElementsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, deprecatedTouchableElements_);
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void clearDeprecatedTouchableElements() {
    deprecatedTouchableElements_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Restrict interaction to the area spanned by the given elements.
   * Deprecated: use touchable_element_area instead. Ignored if
   * touchable_element_area is non-empty.
   * </pre>
   *
   * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
   */
  private void removeDeprecatedTouchableElements(int index) {
    ensureDeprecatedTouchableElementsIsMutable();
    deprecatedTouchableElements_.remove(index);
  }

  public static final int TOUCHABLE_ELEMENT_AREA_FIELD_NUMBER = 6;
  private org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto touchableElementArea_;
  /**
   * <pre>
   * Restrict interaction to a series of rectangular areas.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
   */
  public boolean hasTouchableElementArea() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * Restrict interaction to a series of rectangular areas.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto getTouchableElementArea() {
    return touchableElementArea_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto.getDefaultInstance() : touchableElementArea_;
  }
  /**
   * <pre>
   * Restrict interaction to a series of rectangular areas.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
   */
  private void setTouchableElementArea(org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto value) {
    if (value == null) {
      throw new NullPointerException();
    }
    touchableElementArea_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <pre>
   * Restrict interaction to a series of rectangular areas.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
   */
  private void setTouchableElementArea(
      org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto.Builder builderForValue) {
    touchableElementArea_ = builderForValue.build();
    bitField0_ |= 0x00000004;
  }
  /**
   * <pre>
   * Restrict interaction to a series of rectangular areas.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
   */
  private void mergeTouchableElementArea(org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto value) {
    if (touchableElementArea_ != null &&
        touchableElementArea_ != org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto.getDefaultInstance()) {
      touchableElementArea_ =
        org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto.newBuilder(touchableElementArea_).mergeFrom(value).buildPartial();
    } else {
      touchableElementArea_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <pre>
   * Restrict interaction to a series of rectangular areas.
   * </pre>
   *
   * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
   */
  private void clearTouchableElementArea() {  touchableElementArea_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int TOP_PADDING_FIELD_NUMBER = 7;
  private org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding topPadding_;
  /**
   * <pre>
   * The padding that will be added between the focused element and the top.
   * </pre>
   *
   * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
   */
  public boolean hasTopPadding() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   * The padding that will be added between the focused element and the top.
   * </pre>
   *
   * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding getTopPadding() {
    return topPadding_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.getDefaultInstance() : topPadding_;
  }
  /**
   * <pre>
   * The padding that will be added between the focused element and the top.
   * </pre>
   *
   * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
   */
  private void setTopPadding(org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding value) {
    if (value == null) {
      throw new NullPointerException();
    }
    topPadding_ = value;
    bitField0_ |= 0x00000008;
    }
  /**
   * <pre>
   * The padding that will be added between the focused element and the top.
   * </pre>
   *
   * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
   */
  private void setTopPadding(
      org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.Builder builderForValue) {
    topPadding_ = builderForValue.build();
    bitField0_ |= 0x00000008;
  }
  /**
   * <pre>
   * The padding that will be added between the focused element and the top.
   * </pre>
   *
   * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
   */
  private void mergeTopPadding(org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding value) {
    if (topPadding_ != null &&
        topPadding_ != org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.getDefaultInstance()) {
      topPadding_ =
        org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.newBuilder(topPadding_).mergeFrom(value).buildPartial();
    } else {
      topPadding_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <pre>
   * The padding that will be added between the focused element and the top.
   * </pre>
   *
   * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
   */
  private void clearTopPadding() {  topPadding_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getElement());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeString(2, getTitle());
    }
    for (int i = 0; i < deprecatedTouchableElements_.size(); i++) {
      output.writeMessage(5, deprecatedTouchableElements_.get(i));
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(6, getTouchableElementArea());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(7, getTopPadding());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getElement());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getTitle());
    }
    for (int i = 0; i < deprecatedTouchableElements_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, deprecatedTouchableElements_.get(i));
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTouchableElementArea());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getTopPadding());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Contain all arguments to focus on an element.
   * </pre>
   *
   * Protobuf type {@code autofill_assistant.FocusElementProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:autofill_assistant.FocusElementProto)
      org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProtoOrBuilder {
    // Construct using org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Element to focus on.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public boolean hasElement() {
      return instance.hasElement();
    }
    /**
     * <pre>
     * Element to focus on.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto getElement() {
      return instance.getElement();
    }
    /**
     * <pre>
     * Element to focus on.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public Builder setElement(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
      copyOnWrite();
      instance.setElement(value);
      return this;
      }
    /**
     * <pre>
     * Element to focus on.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public Builder setElement(
        org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
      copyOnWrite();
      instance.setElement(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Element to focus on.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public Builder mergeElement(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
      copyOnWrite();
      instance.mergeElement(value);
      return this;
    }
    /**
     * <pre>
     * Element to focus on.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementReferenceProto element = 1;</code>
     */
    public Builder clearElement() {  copyOnWrite();
      instance.clearElement();
      return this;
    }

    /**
     * <pre>
     * Optional title to show in the status bar.
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    public boolean hasTitle() {
      return instance.hasTitle();
    }
    /**
     * <pre>
     * Optional title to show in the status bar.
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <pre>
     * Optional title to show in the status bar.
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <pre>
     * Optional title to show in the status bar.
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <pre>
     * Optional title to show in the status bar.
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <pre>
     * Optional title to show in the status bar.
     * </pre>
     *
     * <code>optional string title = 2;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public java.util.List<org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto> getDeprecatedTouchableElementsList() {
      return java.util.Collections.unmodifiableList(
          instance.getDeprecatedTouchableElementsList());
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public int getDeprecatedTouchableElementsCount() {
      return instance.getDeprecatedTouchableElementsCount();
    }/**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto getDeprecatedTouchableElements(int index) {
      return instance.getDeprecatedTouchableElements(index);
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder setDeprecatedTouchableElements(
        int index, org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
      copyOnWrite();
      instance.setDeprecatedTouchableElements(index, value);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder setDeprecatedTouchableElements(
        int index, org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
      copyOnWrite();
      instance.setDeprecatedTouchableElements(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder addDeprecatedTouchableElements(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
      copyOnWrite();
      instance.addDeprecatedTouchableElements(value);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder addDeprecatedTouchableElements(
        int index, org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto value) {
      copyOnWrite();
      instance.addDeprecatedTouchableElements(index, value);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder addDeprecatedTouchableElements(
        org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
      copyOnWrite();
      instance.addDeprecatedTouchableElements(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder addDeprecatedTouchableElements(
        int index, org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder builderForValue) {
      copyOnWrite();
      instance.addDeprecatedTouchableElements(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder addAllDeprecatedTouchableElements(
        java.lang.Iterable<? extends org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto> values) {
      copyOnWrite();
      instance.addAllDeprecatedTouchableElements(values);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder clearDeprecatedTouchableElements() {
      copyOnWrite();
      instance.clearDeprecatedTouchableElements();
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to the area spanned by the given elements.
     * Deprecated: use touchable_element_area instead. Ignored if
     * touchable_element_area is non-empty.
     * </pre>
     *
     * <code>repeated .autofill_assistant.ElementReferenceProto deprecated_touchable_elements = 5;</code>
     */
    public Builder removeDeprecatedTouchableElements(int index) {
      copyOnWrite();
      instance.removeDeprecatedTouchableElements(index);
      return this;
    }

    /**
     * <pre>
     * Restrict interaction to a series of rectangular areas.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
     */
    public boolean hasTouchableElementArea() {
      return instance.hasTouchableElementArea();
    }
    /**
     * <pre>
     * Restrict interaction to a series of rectangular areas.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto getTouchableElementArea() {
      return instance.getTouchableElementArea();
    }
    /**
     * <pre>
     * Restrict interaction to a series of rectangular areas.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
     */
    public Builder setTouchableElementArea(org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto value) {
      copyOnWrite();
      instance.setTouchableElementArea(value);
      return this;
      }
    /**
     * <pre>
     * Restrict interaction to a series of rectangular areas.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
     */
    public Builder setTouchableElementArea(
        org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto.Builder builderForValue) {
      copyOnWrite();
      instance.setTouchableElementArea(builderForValue);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to a series of rectangular areas.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
     */
    public Builder mergeTouchableElementArea(org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto value) {
      copyOnWrite();
      instance.mergeTouchableElementArea(value);
      return this;
    }
    /**
     * <pre>
     * Restrict interaction to a series of rectangular areas.
     * </pre>
     *
     * <code>optional .autofill_assistant.ElementAreaProto touchable_element_area = 6;</code>
     */
    public Builder clearTouchableElementArea() {  copyOnWrite();
      instance.clearTouchableElementArea();
      return this;
    }

    /**
     * <pre>
     * The padding that will be added between the focused element and the top.
     * </pre>
     *
     * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
     */
    public boolean hasTopPadding() {
      return instance.hasTopPadding();
    }
    /**
     * <pre>
     * The padding that will be added between the focused element and the top.
     * </pre>
     *
     * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding getTopPadding() {
      return instance.getTopPadding();
    }
    /**
     * <pre>
     * The padding that will be added between the focused element and the top.
     * </pre>
     *
     * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
     */
    public Builder setTopPadding(org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding value) {
      copyOnWrite();
      instance.setTopPadding(value);
      return this;
      }
    /**
     * <pre>
     * The padding that will be added between the focused element and the top.
     * </pre>
     *
     * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
     */
    public Builder setTopPadding(
        org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.Builder builderForValue) {
      copyOnWrite();
      instance.setTopPadding(builderForValue);
      return this;
    }
    /**
     * <pre>
     * The padding that will be added between the focused element and the top.
     * </pre>
     *
     * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
     */
    public Builder mergeTopPadding(org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding value) {
      copyOnWrite();
      instance.mergeTopPadding(value);
      return this;
    }
    /**
     * <pre>
     * The padding that will be added between the focused element and the top.
     * </pre>
     *
     * <code>optional .autofill_assistant.FocusElementProto.TopPadding top_padding = 7;</code>
     */
    public Builder clearTopPadding() {  copyOnWrite();
      instance.clearTopPadding();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:autofill_assistant.FocusElementProto)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        deprecatedTouchableElements_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto other = (org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto) arg1;
        element_ = visitor.visitMessage(element_, other.element_);
        title_ = visitor.visitString(
            hasTitle(), title_,
            other.hasTitle(), other.title_);
        deprecatedTouchableElements_= visitor.visitList(deprecatedTouchableElements_, other.deprecatedTouchableElements_);
        touchableElementArea_ = visitor.visitMessage(touchableElementArea_, other.touchableElementArea_);
        topPadding_ = visitor.visitMessage(topPadding_, other.topPadding_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = element_.toBuilder();
                }
                element_ = input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(element_);
                  element_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
              case 18: {
                String s = input.readString();
                bitField0_ |= 0x00000002;
                title_ = s;
                break;
              }
              case 42: {
                if (!deprecatedTouchableElements_.isModifiable()) {
                  deprecatedTouchableElements_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(deprecatedTouchableElements_);
                }
                deprecatedTouchableElements_.add(
                    input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.ElementReferenceProto.parser(), extensionRegistry));
                break;
              }
              case 50: {
                org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto.Builder subBuilder = null;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                  subBuilder = touchableElementArea_.toBuilder();
                }
                touchableElementArea_ = input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.ElementAreaProto.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(touchableElementArea_);
                  touchableElementArea_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000004;
                break;
              }
              case 58: {
                org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.Builder subBuilder = null;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                  subBuilder = topPadding_.toBuilder();
                }
                topPadding_ = input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.TopPadding.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(topPadding_);
                  topPadding_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000008;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:autofill_assistant.FocusElementProto)
  private static final org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FocusElementProto();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.FocusElementProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FocusElementProto> PARSER;

  public static com.google.protobuf.Parser<FocusElementProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

