// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

public interface InfoBoxProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:autofill_assistant.InfoBoxProto)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Optional path to an image. Ok tick used if not set.
   * </pre>
   *
   * <code>optional string image_path = 1;</code>
   */
  boolean hasImagePath();
  /**
   * <pre>
   * Optional path to an image. Ok tick used if not set.
   * </pre>
   *
   * <code>optional string image_path = 1;</code>
   */
  java.lang.String getImagePath();
  /**
   * <pre>
   * Optional path to an image. Ok tick used if not set.
   * </pre>
   *
   * <code>optional string image_path = 1;</code>
   */
  com.google.protobuf.ByteString
      getImagePathBytes();

  /**
   * <pre>
   * The explanation to show in the box. Not setting this field will clear an
   * existing info box.
   * </pre>
   *
   * <code>optional string explanation = 2;</code>
   */
  boolean hasExplanation();
  /**
   * <pre>
   * The explanation to show in the box. Not setting this field will clear an
   * existing info box.
   * </pre>
   *
   * <code>optional string explanation = 2;</code>
   */
  java.lang.String getExplanation();
  /**
   * <pre>
   * The explanation to show in the box. Not setting this field will clear an
   * existing info box.
   * </pre>
   *
   * <code>optional string explanation = 2;</code>
   */
  com.google.protobuf.ByteString
      getExplanationBytes();
}
