// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

/**
 * <pre>
 * Controls the browser navigation.
 * </pre>
 *
 * Protobuf type {@code autofill_assistant.NavigateProto}
 */
public  final class NavigateProto extends
    com.google.protobuf.GeneratedMessageLite<
        NavigateProto, NavigateProto.Builder> implements
    // @@protoc_insertion_point(message_implements:autofill_assistant.NavigateProto)
    NavigateProtoOrBuilder {
  private NavigateProto() {
  }
  private int bitField0_;
  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite {
    URL(1),
    GO_BACKWARD(2),
    GO_FORWARD(3),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 1: return URL;
        case 2: return GO_BACKWARD;
        case 3: return GO_FORWARD;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  private void clearValue() {
    valueCase_ = 0;
    value_ = null;
  }

  public static final int URL_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Navigate to the given URL.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  public boolean hasUrl() {
    return valueCase_ == 1;
  }
  /**
   * <pre>
   * Navigate to the given URL.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  public java.lang.String getUrl() {
    java.lang.String ref = "";
    if (valueCase_ == 1) {
      ref = (java.lang.String) value_;
    }
    return ref;
  }
  /**
   * <pre>
   * Navigate to the given URL.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.String ref = "";
    if (valueCase_ == 1) {
      ref = (java.lang.String) value_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <pre>
   * Navigate to the given URL.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  private void setUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 1;
    value_ = value;
  }
  /**
   * <pre>
   * Navigate to the given URL.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  private void clearUrl() {
    if (valueCase_ == 1) {
      valueCase_ = 0;
      value_ = null;
    }
  }
  /**
   * <pre>
   * Navigate to the given URL.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  private void setUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 1;
    value_ = value.toStringUtf8();
  }

  public static final int GO_BACKWARD_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Navigate backward in the history. Action will return PRECONDITION_FAILED
   * if it is not possible.
   * </pre>
   *
   * <code>optional bool go_backward = 2;</code>
   */
  public boolean hasGoBackward() {
    return valueCase_ == 2;
  }
  /**
   * <pre>
   * Navigate backward in the history. Action will return PRECONDITION_FAILED
   * if it is not possible.
   * </pre>
   *
   * <code>optional bool go_backward = 2;</code>
   */
  public boolean getGoBackward() {
    if (valueCase_ == 2) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }
  /**
   * <pre>
   * Navigate backward in the history. Action will return PRECONDITION_FAILED
   * if it is not possible.
   * </pre>
   *
   * <code>optional bool go_backward = 2;</code>
   */
  private void setGoBackward(boolean value) {
    valueCase_ = 2;
    value_ = value;
  }
  /**
   * <pre>
   * Navigate backward in the history. Action will return PRECONDITION_FAILED
   * if it is not possible.
   * </pre>
   *
   * <code>optional bool go_backward = 2;</code>
   */
  private void clearGoBackward() {
    if (valueCase_ == 2) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int GO_FORWARD_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Navigate forward in the history. Action will return PRECONDITION_FAILED
   * if it is not possible.
   * </pre>
   *
   * <code>optional bool go_forward = 3;</code>
   */
  public boolean hasGoForward() {
    return valueCase_ == 3;
  }
  /**
   * <pre>
   * Navigate forward in the history. Action will return PRECONDITION_FAILED
   * if it is not possible.
   * </pre>
   *
   * <code>optional bool go_forward = 3;</code>
   */
  public boolean getGoForward() {
    if (valueCase_ == 3) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }
  /**
   * <pre>
   * Navigate forward in the history. Action will return PRECONDITION_FAILED
   * if it is not possible.
   * </pre>
   *
   * <code>optional bool go_forward = 3;</code>
   */
  private void setGoForward(boolean value) {
    valueCase_ = 3;
    value_ = value;
  }
  /**
   * <pre>
   * Navigate forward in the history. Action will return PRECONDITION_FAILED
   * if it is not possible.
   * </pre>
   *
   * <code>optional bool go_forward = 3;</code>
   */
  private void clearGoForward() {
    if (valueCase_ == 3) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valueCase_ == 1) {
      output.writeString(1, getUrl());
    }
    if (valueCase_ == 2) {
      output.writeBool(
          2, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 3) {
      output.writeBool(
          3, (boolean)((java.lang.Boolean) value_));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (valueCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getUrl());
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            2, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            3, (boolean)((java.lang.Boolean) value_));
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Controls the browser navigation.
   * </pre>
   *
   * Protobuf type {@code autofill_assistant.NavigateProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:autofill_assistant.NavigateProto)
      org.chromium.chrome.browser.autofill_assistant.proto.NavigateProtoOrBuilder {
    // Construct using org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public ValueCase
        getValueCase() {
      return instance.getValueCase();
    }

    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }


    /**
     * <pre>
     * Navigate to the given URL.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public boolean hasUrl() {
      return instance.hasUrl();
    }
    /**
     * <pre>
     * Navigate to the given URL.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public java.lang.String getUrl() {
      return instance.getUrl();
    }
    /**
     * <pre>
     * Navigate to the given URL.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return instance.getUrlBytes();
    }
    /**
     * <pre>
     * Navigate to the given URL.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl(value);
      return this;
    }
    /**
     * <pre>
     * Navigate to the given URL.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public Builder clearUrl() {
      copyOnWrite();
      instance.clearUrl();
      return this;
    }
    /**
     * <pre>
     * Navigate to the given URL.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrlBytes(value);
      return this;
    }

    /**
     * <pre>
     * Navigate backward in the history. Action will return PRECONDITION_FAILED
     * if it is not possible.
     * </pre>
     *
     * <code>optional bool go_backward = 2;</code>
     */
    public boolean hasGoBackward() {
      return instance.hasGoBackward();
    }
    /**
     * <pre>
     * Navigate backward in the history. Action will return PRECONDITION_FAILED
     * if it is not possible.
     * </pre>
     *
     * <code>optional bool go_backward = 2;</code>
     */
    public boolean getGoBackward() {
      return instance.getGoBackward();
    }
    /**
     * <pre>
     * Navigate backward in the history. Action will return PRECONDITION_FAILED
     * if it is not possible.
     * </pre>
     *
     * <code>optional bool go_backward = 2;</code>
     */
    public Builder setGoBackward(boolean value) {
      copyOnWrite();
      instance.setGoBackward(value);
      return this;
    }
    /**
     * <pre>
     * Navigate backward in the history. Action will return PRECONDITION_FAILED
     * if it is not possible.
     * </pre>
     *
     * <code>optional bool go_backward = 2;</code>
     */
    public Builder clearGoBackward() {
      copyOnWrite();
      instance.clearGoBackward();
      return this;
    }

    /**
     * <pre>
     * Navigate forward in the history. Action will return PRECONDITION_FAILED
     * if it is not possible.
     * </pre>
     *
     * <code>optional bool go_forward = 3;</code>
     */
    public boolean hasGoForward() {
      return instance.hasGoForward();
    }
    /**
     * <pre>
     * Navigate forward in the history. Action will return PRECONDITION_FAILED
     * if it is not possible.
     * </pre>
     *
     * <code>optional bool go_forward = 3;</code>
     */
    public boolean getGoForward() {
      return instance.getGoForward();
    }
    /**
     * <pre>
     * Navigate forward in the history. Action will return PRECONDITION_FAILED
     * if it is not possible.
     * </pre>
     *
     * <code>optional bool go_forward = 3;</code>
     */
    public Builder setGoForward(boolean value) {
      copyOnWrite();
      instance.setGoForward(value);
      return this;
    }
    /**
     * <pre>
     * Navigate forward in the history. Action will return PRECONDITION_FAILED
     * if it is not possible.
     * </pre>
     *
     * <code>optional bool go_forward = 3;</code>
     */
    public Builder clearGoForward() {
      copyOnWrite();
      instance.clearGoForward();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:autofill_assistant.NavigateProto)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto other = (org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto) arg1;
        switch (other.getValueCase()) {
          case URL: {
            value_ = visitor.visitOneofString(
               valueCase_ == 1, value_, other.value_);
            break;
          }
          case GO_BACKWARD: {
            value_ = visitor.visitOneofBoolean(
                valueCase_ == 2, value_, other.value_);
            break;
          }
          case GO_FORWARD: {
            value_ = visitor.visitOneofBoolean(
                valueCase_ == 3, value_, other.value_);
            break;
          }
          case VALUE_NOT_SET: {
            visitor.visitOneofNotSet(valueCase_ != 0);
            break;
          }
        }
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          if (other.valueCase_ != 0) {
            valueCase_ = other.valueCase_;
          }
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                valueCase_ = 1;
                value_ = s;
                break;
              }
              case 16: {
                valueCase_ = 2;
                value_ = input.readBool();
                break;
              }
              case 24: {
                valueCase_ = 3;
                value_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:autofill_assistant.NavigateProto)
  private static final org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NavigateProto();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.NavigateProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NavigateProto> PARSER;

  public static com.google.protobuf.Parser<NavigateProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

