// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

/**
 * Protobuf type {@code autofill_assistant.ScriptTimeoutError}
 */
public  final class ScriptTimeoutError extends
    com.google.protobuf.GeneratedMessageLite<
        ScriptTimeoutError, ScriptTimeoutError.Builder> implements
    // @@protoc_insertion_point(message_implements:autofill_assistant.ScriptTimeoutError)
    ScriptTimeoutErrorOrBuilder {
  private ScriptTimeoutError() {
    scriptPath_ = "";
  }
  private int bitField0_;
  public static final int TIMEOUT_MS_FIELD_NUMBER = 1;
  private int timeoutMs_;
  /**
   * <pre>
   * Wait for that long before considering that scripts preconditions have timed
   * out and executing the script specified in script_path.
   * The script might be called more than once if the script terminates
   * successfully and again still nothing is found after timeout_ms.
   * </pre>
   *
   * <code>optional int32 timeout_ms = 1;</code>
   */
  public boolean hasTimeoutMs() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * Wait for that long before considering that scripts preconditions have timed
   * out and executing the script specified in script_path.
   * The script might be called more than once if the script terminates
   * successfully and again still nothing is found after timeout_ms.
   * </pre>
   *
   * <code>optional int32 timeout_ms = 1;</code>
   */
  public int getTimeoutMs() {
    return timeoutMs_;
  }
  /**
   * <pre>
   * Wait for that long before considering that scripts preconditions have timed
   * out and executing the script specified in script_path.
   * The script might be called more than once if the script terminates
   * successfully and again still nothing is found after timeout_ms.
   * </pre>
   *
   * <code>optional int32 timeout_ms = 1;</code>
   */
  private void setTimeoutMs(int value) {
    bitField0_ |= 0x00000001;
    timeoutMs_ = value;
  }
  /**
   * <pre>
   * Wait for that long before considering that scripts preconditions have timed
   * out and executing the script specified in script_path.
   * The script might be called more than once if the script terminates
   * successfully and again still nothing is found after timeout_ms.
   * </pre>
   *
   * <code>optional int32 timeout_ms = 1;</code>
   */
  private void clearTimeoutMs() {
    bitField0_ = (bitField0_ & ~0x00000001);
    timeoutMs_ = 0;
  }

  public static final int SCRIPT_PATH_FIELD_NUMBER = 2;
  private java.lang.String scriptPath_;
  /**
   * <pre>
   * The script to execute when the error happens.
   * </pre>
   *
   * <code>optional string script_path = 2;</code>
   */
  public boolean hasScriptPath() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * The script to execute when the error happens.
   * </pre>
   *
   * <code>optional string script_path = 2;</code>
   */
  public java.lang.String getScriptPath() {
    return scriptPath_;
  }
  /**
   * <pre>
   * The script to execute when the error happens.
   * </pre>
   *
   * <code>optional string script_path = 2;</code>
   */
  public com.google.protobuf.ByteString
      getScriptPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(scriptPath_);
  }
  /**
   * <pre>
   * The script to execute when the error happens.
   * </pre>
   *
   * <code>optional string script_path = 2;</code>
   */
  private void setScriptPath(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    scriptPath_ = value;
  }
  /**
   * <pre>
   * The script to execute when the error happens.
   * </pre>
   *
   * <code>optional string script_path = 2;</code>
   */
  private void clearScriptPath() {
    bitField0_ = (bitField0_ & ~0x00000002);
    scriptPath_ = getDefaultInstance().getScriptPath();
  }
  /**
   * <pre>
   * The script to execute when the error happens.
   * </pre>
   *
   * <code>optional string script_path = 2;</code>
   */
  private void setScriptPathBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    scriptPath_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, timeoutMs_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeString(2, getScriptPath());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, timeoutMs_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getScriptPath());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code autofill_assistant.ScriptTimeoutError}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError, Builder> implements
      // @@protoc_insertion_point(builder_implements:autofill_assistant.ScriptTimeoutError)
      org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutErrorOrBuilder {
    // Construct using org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Wait for that long before considering that scripts preconditions have timed
     * out and executing the script specified in script_path.
     * The script might be called more than once if the script terminates
     * successfully and again still nothing is found after timeout_ms.
     * </pre>
     *
     * <code>optional int32 timeout_ms = 1;</code>
     */
    public boolean hasTimeoutMs() {
      return instance.hasTimeoutMs();
    }
    /**
     * <pre>
     * Wait for that long before considering that scripts preconditions have timed
     * out and executing the script specified in script_path.
     * The script might be called more than once if the script terminates
     * successfully and again still nothing is found after timeout_ms.
     * </pre>
     *
     * <code>optional int32 timeout_ms = 1;</code>
     */
    public int getTimeoutMs() {
      return instance.getTimeoutMs();
    }
    /**
     * <pre>
     * Wait for that long before considering that scripts preconditions have timed
     * out and executing the script specified in script_path.
     * The script might be called more than once if the script terminates
     * successfully and again still nothing is found after timeout_ms.
     * </pre>
     *
     * <code>optional int32 timeout_ms = 1;</code>
     */
    public Builder setTimeoutMs(int value) {
      copyOnWrite();
      instance.setTimeoutMs(value);
      return this;
    }
    /**
     * <pre>
     * Wait for that long before considering that scripts preconditions have timed
     * out and executing the script specified in script_path.
     * The script might be called more than once if the script terminates
     * successfully and again still nothing is found after timeout_ms.
     * </pre>
     *
     * <code>optional int32 timeout_ms = 1;</code>
     */
    public Builder clearTimeoutMs() {
      copyOnWrite();
      instance.clearTimeoutMs();
      return this;
    }

    /**
     * <pre>
     * The script to execute when the error happens.
     * </pre>
     *
     * <code>optional string script_path = 2;</code>
     */
    public boolean hasScriptPath() {
      return instance.hasScriptPath();
    }
    /**
     * <pre>
     * The script to execute when the error happens.
     * </pre>
     *
     * <code>optional string script_path = 2;</code>
     */
    public java.lang.String getScriptPath() {
      return instance.getScriptPath();
    }
    /**
     * <pre>
     * The script to execute when the error happens.
     * </pre>
     *
     * <code>optional string script_path = 2;</code>
     */
    public com.google.protobuf.ByteString
        getScriptPathBytes() {
      return instance.getScriptPathBytes();
    }
    /**
     * <pre>
     * The script to execute when the error happens.
     * </pre>
     *
     * <code>optional string script_path = 2;</code>
     */
    public Builder setScriptPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setScriptPath(value);
      return this;
    }
    /**
     * <pre>
     * The script to execute when the error happens.
     * </pre>
     *
     * <code>optional string script_path = 2;</code>
     */
    public Builder clearScriptPath() {
      copyOnWrite();
      instance.clearScriptPath();
      return this;
    }
    /**
     * <pre>
     * The script to execute when the error happens.
     * </pre>
     *
     * <code>optional string script_path = 2;</code>
     */
    public Builder setScriptPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setScriptPathBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:autofill_assistant.ScriptTimeoutError)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError other = (org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError) arg1;
        timeoutMs_ = visitor.visitInt(
            hasTimeoutMs(), timeoutMs_,
            other.hasTimeoutMs(), other.timeoutMs_);
        scriptPath_ = visitor.visitString(
            hasScriptPath(), scriptPath_,
            other.hasScriptPath(), other.scriptPath_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                timeoutMs_ = input.readInt32();
                break;
              }
              case 18: {
                String s = input.readString();
                bitField0_ |= 0x00000002;
                scriptPath_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:autofill_assistant.ScriptTimeoutError)
  private static final org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ScriptTimeoutError();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.ScriptTimeoutError getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ScriptTimeoutError> PARSER;

  public static com.google.protobuf.Parser<ScriptTimeoutError> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

