// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.chromium.chrome.browser.autofill_assistant.proto;

/**
 * <pre>
 * Supported script.
 * </pre>
 *
 * Protobuf type {@code autofill_assistant.SupportedScriptProto}
 */
public  final class SupportedScriptProto extends
    com.google.protobuf.GeneratedMessageLite<
        SupportedScriptProto, SupportedScriptProto.Builder> implements
    // @@protoc_insertion_point(message_implements:autofill_assistant.SupportedScriptProto)
    SupportedScriptProtoOrBuilder {
  private SupportedScriptProto() {
    path_ = "";
  }
  public interface PresentationProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:autofill_assistant.SupportedScriptProto.PresentationProto)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Precondition contains a set of conditions that must hold for a script to
     * be executed. No precondition means that a script can run in any case.
     * </pre>
     *
     * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
     */
    boolean hasPrecondition();
    /**
     * <pre>
     * Precondition contains a set of conditions that must hold for a script to
     * be executed. No precondition means that a script can run in any case.
     * </pre>
     *
     * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
     */
    org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto getPrecondition();

    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    boolean hasInitialPrompt();
    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    java.lang.String getInitialPrompt();
    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    com.google.protobuf.ByteString
        getInitialPromptBytes();

    /**
     * <pre>
     * Display priority of the script. Lowest number has highest priority, which
     * means a script with priority 0 should be displayed before a script with
     * priority 1.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     */
    boolean hasPriority();
    /**
     * <pre>
     * Display priority of the script. Lowest number has highest priority, which
     * means a script with priority 0 should be displayed before a script with
     * priority 1.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     */
    int getPriority();

    /**
     * <pre>
     * An optional chip to display.
     * </pre>
     *
     * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
     */
    boolean hasChip();
    /**
     * <pre>
     * An optional chip to display.
     * </pre>
     *
     * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
     */
    org.chromium.chrome.browser.autofill_assistant.proto.ChipProto getChip();

    /**
     * <pre>
     * Optionally map this script to a direct action.
     * </pre>
     *
     * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
     */
    boolean hasDirectAction();
    /**
     * <pre>
     * Optionally map this script to a direct action.
     * </pre>
     *
     * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
     */
    org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto getDirectAction();

    /**
     * <pre>
     * When set to true this script can be run in 'autostart mode'.
     * </pre>
     *
     * <code>optional bool autostart = 8;</code>
     */
    boolean hasAutostart();
    /**
     * <pre>
     * When set to true this script can be run in 'autostart mode'.
     * </pre>
     *
     * <code>optional bool autostart = 8;</code>
     */
    boolean getAutostart();

    /**
     * <pre>
     * When set to true this script will be run from WaitForDom actions with
     * allow_interrupt=true.
     * </pre>
     *
     * <code>optional bool interrupt = 9;</code>
     */
    boolean hasInterrupt();
    /**
     * <pre>
     * When set to true this script will be run from WaitForDom actions with
     * allow_interrupt=true.
     * </pre>
     *
     * <code>optional bool interrupt = 9;</code>
     */
    boolean getInterrupt();

    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    boolean hasStartMessage();
    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    java.lang.String getStartMessage();
    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    com.google.protobuf.ByteString
        getStartMessageBytes();

    /**
     * <pre>
     * Show the UI if it's not shown yet. Setting this to false is useful for
     * scripts started by direct actions.
     * </pre>
     *
     * <code>optional bool needs_ui = 15 [default = true];</code>
     */
    boolean hasNeedsUi();
    /**
     * <pre>
     * Show the UI if it's not shown yet. Setting this to false is useful for
     * scripts started by direct actions.
     * </pre>
     *
     * <code>optional bool needs_ui = 15 [default = true];</code>
     */
    boolean getNeedsUi();
  }
  /**
   * Protobuf type {@code autofill_assistant.SupportedScriptProto.PresentationProto}
   */
  public  static final class PresentationProto extends
      com.google.protobuf.GeneratedMessageLite<
          PresentationProto, PresentationProto.Builder> implements
      // @@protoc_insertion_point(message_implements:autofill_assistant.SupportedScriptProto.PresentationProto)
      PresentationProtoOrBuilder {
    private PresentationProto() {
      initialPrompt_ = "";
      startMessage_ = "";
      needsUi_ = true;
    }
    private int bitField0_;
    public static final int PRECONDITION_FIELD_NUMBER = 3;
    private org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto precondition_;
    /**
     * <pre>
     * Precondition contains a set of conditions that must hold for a script to
     * be executed. No precondition means that a script can run in any case.
     * </pre>
     *
     * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
     */
    public boolean hasPrecondition() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * Precondition contains a set of conditions that must hold for a script to
     * be executed. No precondition means that a script can run in any case.
     * </pre>
     *
     * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto getPrecondition() {
      return precondition_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto.getDefaultInstance() : precondition_;
    }
    /**
     * <pre>
     * Precondition contains a set of conditions that must hold for a script to
     * be executed. No precondition means that a script can run in any case.
     * </pre>
     *
     * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
     */
    private void setPrecondition(org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      precondition_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <pre>
     * Precondition contains a set of conditions that must hold for a script to
     * be executed. No precondition means that a script can run in any case.
     * </pre>
     *
     * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
     */
    private void setPrecondition(
        org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto.Builder builderForValue) {
      precondition_ = builderForValue.build();
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Precondition contains a set of conditions that must hold for a script to
     * be executed. No precondition means that a script can run in any case.
     * </pre>
     *
     * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
     */
    private void mergePrecondition(org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto value) {
      if (precondition_ != null &&
          precondition_ != org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto.getDefaultInstance()) {
        precondition_ =
          org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto.newBuilder(precondition_).mergeFrom(value).buildPartial();
      } else {
        precondition_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Precondition contains a set of conditions that must hold for a script to
     * be executed. No precondition means that a script can run in any case.
     * </pre>
     *
     * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
     */
    private void clearPrecondition() {  precondition_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int INITIAL_PROMPT_FIELD_NUMBER = 4;
    private java.lang.String initialPrompt_;
    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    public boolean hasInitialPrompt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    public java.lang.String getInitialPrompt() {
      return initialPrompt_;
    }
    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    public com.google.protobuf.ByteString
        getInitialPromptBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(initialPrompt_);
    }
    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    private void setInitialPrompt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      initialPrompt_ = value;
    }
    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    private void clearInitialPrompt() {
      bitField0_ = (bitField0_ & ~0x00000002);
      initialPrompt_ = getDefaultInstance().getInitialPrompt();
    }
    /**
     * <pre>
     * Text display at the same time as the script is proposed. If more than one
     * script has an initial prompt, the prompt of the highest-priority script
     * wins.
     * </pre>
     *
     * <code>optional string initial_prompt = 4;</code>
     */
    private void setInitialPromptBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      initialPrompt_ = value.toStringUtf8();
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private int priority_;
    /**
     * <pre>
     * Display priority of the script. Lowest number has highest priority, which
     * means a script with priority 0 should be displayed before a script with
     * priority 1.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Display priority of the script. Lowest number has highest priority, which
     * means a script with priority 0 should be displayed before a script with
     * priority 1.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     */
    public int getPriority() {
      return priority_;
    }
    /**
     * <pre>
     * Display priority of the script. Lowest number has highest priority, which
     * means a script with priority 0 should be displayed before a script with
     * priority 1.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     */
    private void setPriority(int value) {
      bitField0_ |= 0x00000004;
      priority_ = value;
    }
    /**
     * <pre>
     * Display priority of the script. Lowest number has highest priority, which
     * means a script with priority 0 should be displayed before a script with
     * priority 1.
     * </pre>
     *
     * <code>optional int32 priority = 5;</code>
     */
    private void clearPriority() {
      bitField0_ = (bitField0_ & ~0x00000004);
      priority_ = 0;
    }

    public static final int CHIP_FIELD_NUMBER = 12;
    private org.chromium.chrome.browser.autofill_assistant.proto.ChipProto chip_;
    /**
     * <pre>
     * An optional chip to display.
     * </pre>
     *
     * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
     */
    public boolean hasChip() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * An optional chip to display.
     * </pre>
     *
     * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.ChipProto getChip() {
      return chip_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.ChipProto.getDefaultInstance() : chip_;
    }
    /**
     * <pre>
     * An optional chip to display.
     * </pre>
     *
     * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
     */
    private void setChip(org.chromium.chrome.browser.autofill_assistant.proto.ChipProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      chip_ = value;
      bitField0_ |= 0x00000008;
      }
    /**
     * <pre>
     * An optional chip to display.
     * </pre>
     *
     * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
     */
    private void setChip(
        org.chromium.chrome.browser.autofill_assistant.proto.ChipProto.Builder builderForValue) {
      chip_ = builderForValue.build();
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * An optional chip to display.
     * </pre>
     *
     * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
     */
    private void mergeChip(org.chromium.chrome.browser.autofill_assistant.proto.ChipProto value) {
      if (chip_ != null &&
          chip_ != org.chromium.chrome.browser.autofill_assistant.proto.ChipProto.getDefaultInstance()) {
        chip_ =
          org.chromium.chrome.browser.autofill_assistant.proto.ChipProto.newBuilder(chip_).mergeFrom(value).buildPartial();
      } else {
        chip_ = value;
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * An optional chip to display.
     * </pre>
     *
     * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
     */
    private void clearChip() {  chip_ = null;
      bitField0_ = (bitField0_ & ~0x00000008);
    }

    public static final int DIRECT_ACTION_FIELD_NUMBER = 13;
    private org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto directAction_;
    /**
     * <pre>
     * Optionally map this script to a direct action.
     * </pre>
     *
     * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
     */
    public boolean hasDirectAction() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * Optionally map this script to a direct action.
     * </pre>
     *
     * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto getDirectAction() {
      return directAction_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto.getDefaultInstance() : directAction_;
    }
    /**
     * <pre>
     * Optionally map this script to a direct action.
     * </pre>
     *
     * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
     */
    private void setDirectAction(org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      directAction_ = value;
      bitField0_ |= 0x00000010;
      }
    /**
     * <pre>
     * Optionally map this script to a direct action.
     * </pre>
     *
     * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
     */
    private void setDirectAction(
        org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto.Builder builderForValue) {
      directAction_ = builderForValue.build();
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * Optionally map this script to a direct action.
     * </pre>
     *
     * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
     */
    private void mergeDirectAction(org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto value) {
      if (directAction_ != null &&
          directAction_ != org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto.getDefaultInstance()) {
        directAction_ =
          org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto.newBuilder(directAction_).mergeFrom(value).buildPartial();
      } else {
        directAction_ = value;
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * Optionally map this script to a direct action.
     * </pre>
     *
     * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
     */
    private void clearDirectAction() {  directAction_ = null;
      bitField0_ = (bitField0_ & ~0x00000010);
    }

    public static final int AUTOSTART_FIELD_NUMBER = 8;
    private boolean autostart_;
    /**
     * <pre>
     * When set to true this script can be run in 'autostart mode'.
     * </pre>
     *
     * <code>optional bool autostart = 8;</code>
     */
    public boolean hasAutostart() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * When set to true this script can be run in 'autostart mode'.
     * </pre>
     *
     * <code>optional bool autostart = 8;</code>
     */
    public boolean getAutostart() {
      return autostart_;
    }
    /**
     * <pre>
     * When set to true this script can be run in 'autostart mode'.
     * </pre>
     *
     * <code>optional bool autostart = 8;</code>
     */
    private void setAutostart(boolean value) {
      bitField0_ |= 0x00000020;
      autostart_ = value;
    }
    /**
     * <pre>
     * When set to true this script can be run in 'autostart mode'.
     * </pre>
     *
     * <code>optional bool autostart = 8;</code>
     */
    private void clearAutostart() {
      bitField0_ = (bitField0_ & ~0x00000020);
      autostart_ = false;
    }

    public static final int INTERRUPT_FIELD_NUMBER = 9;
    private boolean interrupt_;
    /**
     * <pre>
     * When set to true this script will be run from WaitForDom actions with
     * allow_interrupt=true.
     * </pre>
     *
     * <code>optional bool interrupt = 9;</code>
     */
    public boolean hasInterrupt() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * When set to true this script will be run from WaitForDom actions with
     * allow_interrupt=true.
     * </pre>
     *
     * <code>optional bool interrupt = 9;</code>
     */
    public boolean getInterrupt() {
      return interrupt_;
    }
    /**
     * <pre>
     * When set to true this script will be run from WaitForDom actions with
     * allow_interrupt=true.
     * </pre>
     *
     * <code>optional bool interrupt = 9;</code>
     */
    private void setInterrupt(boolean value) {
      bitField0_ |= 0x00000040;
      interrupt_ = value;
    }
    /**
     * <pre>
     * When set to true this script will be run from WaitForDom actions with
     * allow_interrupt=true.
     * </pre>
     *
     * <code>optional bool interrupt = 9;</code>
     */
    private void clearInterrupt() {
      bitField0_ = (bitField0_ & ~0x00000040);
      interrupt_ = false;
    }

    public static final int START_MESSAGE_FIELD_NUMBER = 14;
    private java.lang.String startMessage_;
    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    public boolean hasStartMessage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    public java.lang.String getStartMessage() {
      return startMessage_;
    }
    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    public com.google.protobuf.ByteString
        getStartMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(startMessage_);
    }
    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    private void setStartMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      startMessage_ = value;
    }
    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    private void clearStartMessage() {
      bitField0_ = (bitField0_ & ~0x00000080);
      startMessage_ = getDefaultInstance().getStartMessage();
    }
    /**
     * <pre>
     * Message to show once the script has been started. This is shown while
     * loading the actions.
     * </pre>
     *
     * <code>optional string start_message = 14;</code>
     */
    private void setStartMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      startMessage_ = value.toStringUtf8();
    }

    public static final int NEEDS_UI_FIELD_NUMBER = 15;
    private boolean needsUi_;
    /**
     * <pre>
     * Show the UI if it's not shown yet. Setting this to false is useful for
     * scripts started by direct actions.
     * </pre>
     *
     * <code>optional bool needs_ui = 15 [default = true];</code>
     */
    public boolean hasNeedsUi() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     * Show the UI if it's not shown yet. Setting this to false is useful for
     * scripts started by direct actions.
     * </pre>
     *
     * <code>optional bool needs_ui = 15 [default = true];</code>
     */
    public boolean getNeedsUi() {
      return needsUi_;
    }
    /**
     * <pre>
     * Show the UI if it's not shown yet. Setting this to false is useful for
     * scripts started by direct actions.
     * </pre>
     *
     * <code>optional bool needs_ui = 15 [default = true];</code>
     */
    private void setNeedsUi(boolean value) {
      bitField0_ |= 0x00000100;
      needsUi_ = value;
    }
    /**
     * <pre>
     * Show the UI if it's not shown yet. Setting this to false is useful for
     * scripts started by direct actions.
     * </pre>
     *
     * <code>optional bool needs_ui = 15 [default = true];</code>
     */
    private void clearNeedsUi() {
      bitField0_ = (bitField0_ & ~0x00000100);
      needsUi_ = true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(3, getPrecondition());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(4, getInitialPrompt());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(5, priority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(8, autostart_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(9, interrupt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(12, getChip());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(13, getDirectAction());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeString(14, getStartMessage());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(15, needsUi_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getPrecondition());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getInitialPrompt());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, priority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, autostart_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, interrupt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getChip());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getDirectAction());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getStartMessage());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, needsUi_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code autofill_assistant.SupportedScriptProto.PresentationProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto, Builder> implements
        // @@protoc_insertion_point(builder_implements:autofill_assistant.SupportedScriptProto.PresentationProto)
        org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProtoOrBuilder {
      // Construct using org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Precondition contains a set of conditions that must hold for a script to
       * be executed. No precondition means that a script can run in any case.
       * </pre>
       *
       * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
       */
      public boolean hasPrecondition() {
        return instance.hasPrecondition();
      }
      /**
       * <pre>
       * Precondition contains a set of conditions that must hold for a script to
       * be executed. No precondition means that a script can run in any case.
       * </pre>
       *
       * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
       */
      public org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto getPrecondition() {
        return instance.getPrecondition();
      }
      /**
       * <pre>
       * Precondition contains a set of conditions that must hold for a script to
       * be executed. No precondition means that a script can run in any case.
       * </pre>
       *
       * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
       */
      public Builder setPrecondition(org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto value) {
        copyOnWrite();
        instance.setPrecondition(value);
        return this;
        }
      /**
       * <pre>
       * Precondition contains a set of conditions that must hold for a script to
       * be executed. No precondition means that a script can run in any case.
       * </pre>
       *
       * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
       */
      public Builder setPrecondition(
          org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto.Builder builderForValue) {
        copyOnWrite();
        instance.setPrecondition(builderForValue);
        return this;
      }
      /**
       * <pre>
       * Precondition contains a set of conditions that must hold for a script to
       * be executed. No precondition means that a script can run in any case.
       * </pre>
       *
       * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
       */
      public Builder mergePrecondition(org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto value) {
        copyOnWrite();
        instance.mergePrecondition(value);
        return this;
      }
      /**
       * <pre>
       * Precondition contains a set of conditions that must hold for a script to
       * be executed. No precondition means that a script can run in any case.
       * </pre>
       *
       * <code>optional .autofill_assistant.ScriptPreconditionProto precondition = 3;</code>
       */
      public Builder clearPrecondition() {  copyOnWrite();
        instance.clearPrecondition();
        return this;
      }

      /**
       * <pre>
       * Text display at the same time as the script is proposed. If more than one
       * script has an initial prompt, the prompt of the highest-priority script
       * wins.
       * </pre>
       *
       * <code>optional string initial_prompt = 4;</code>
       */
      public boolean hasInitialPrompt() {
        return instance.hasInitialPrompt();
      }
      /**
       * <pre>
       * Text display at the same time as the script is proposed. If more than one
       * script has an initial prompt, the prompt of the highest-priority script
       * wins.
       * </pre>
       *
       * <code>optional string initial_prompt = 4;</code>
       */
      public java.lang.String getInitialPrompt() {
        return instance.getInitialPrompt();
      }
      /**
       * <pre>
       * Text display at the same time as the script is proposed. If more than one
       * script has an initial prompt, the prompt of the highest-priority script
       * wins.
       * </pre>
       *
       * <code>optional string initial_prompt = 4;</code>
       */
      public com.google.protobuf.ByteString
          getInitialPromptBytes() {
        return instance.getInitialPromptBytes();
      }
      /**
       * <pre>
       * Text display at the same time as the script is proposed. If more than one
       * script has an initial prompt, the prompt of the highest-priority script
       * wins.
       * </pre>
       *
       * <code>optional string initial_prompt = 4;</code>
       */
      public Builder setInitialPrompt(
          java.lang.String value) {
        copyOnWrite();
        instance.setInitialPrompt(value);
        return this;
      }
      /**
       * <pre>
       * Text display at the same time as the script is proposed. If more than one
       * script has an initial prompt, the prompt of the highest-priority script
       * wins.
       * </pre>
       *
       * <code>optional string initial_prompt = 4;</code>
       */
      public Builder clearInitialPrompt() {
        copyOnWrite();
        instance.clearInitialPrompt();
        return this;
      }
      /**
       * <pre>
       * Text display at the same time as the script is proposed. If more than one
       * script has an initial prompt, the prompt of the highest-priority script
       * wins.
       * </pre>
       *
       * <code>optional string initial_prompt = 4;</code>
       */
      public Builder setInitialPromptBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setInitialPromptBytes(value);
        return this;
      }

      /**
       * <pre>
       * Display priority of the script. Lowest number has highest priority, which
       * means a script with priority 0 should be displayed before a script with
       * priority 1.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       */
      public boolean hasPriority() {
        return instance.hasPriority();
      }
      /**
       * <pre>
       * Display priority of the script. Lowest number has highest priority, which
       * means a script with priority 0 should be displayed before a script with
       * priority 1.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       */
      public int getPriority() {
        return instance.getPriority();
      }
      /**
       * <pre>
       * Display priority of the script. Lowest number has highest priority, which
       * means a script with priority 0 should be displayed before a script with
       * priority 1.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       */
      public Builder setPriority(int value) {
        copyOnWrite();
        instance.setPriority(value);
        return this;
      }
      /**
       * <pre>
       * Display priority of the script. Lowest number has highest priority, which
       * means a script with priority 0 should be displayed before a script with
       * priority 1.
       * </pre>
       *
       * <code>optional int32 priority = 5;</code>
       */
      public Builder clearPriority() {
        copyOnWrite();
        instance.clearPriority();
        return this;
      }

      /**
       * <pre>
       * An optional chip to display.
       * </pre>
       *
       * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
       */
      public boolean hasChip() {
        return instance.hasChip();
      }
      /**
       * <pre>
       * An optional chip to display.
       * </pre>
       *
       * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
       */
      public org.chromium.chrome.browser.autofill_assistant.proto.ChipProto getChip() {
        return instance.getChip();
      }
      /**
       * <pre>
       * An optional chip to display.
       * </pre>
       *
       * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
       */
      public Builder setChip(org.chromium.chrome.browser.autofill_assistant.proto.ChipProto value) {
        copyOnWrite();
        instance.setChip(value);
        return this;
        }
      /**
       * <pre>
       * An optional chip to display.
       * </pre>
       *
       * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
       */
      public Builder setChip(
          org.chromium.chrome.browser.autofill_assistant.proto.ChipProto.Builder builderForValue) {
        copyOnWrite();
        instance.setChip(builderForValue);
        return this;
      }
      /**
       * <pre>
       * An optional chip to display.
       * </pre>
       *
       * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
       */
      public Builder mergeChip(org.chromium.chrome.browser.autofill_assistant.proto.ChipProto value) {
        copyOnWrite();
        instance.mergeChip(value);
        return this;
      }
      /**
       * <pre>
       * An optional chip to display.
       * </pre>
       *
       * <code>optional .autofill_assistant.ChipProto chip = 12;</code>
       */
      public Builder clearChip() {  copyOnWrite();
        instance.clearChip();
        return this;
      }

      /**
       * <pre>
       * Optionally map this script to a direct action.
       * </pre>
       *
       * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
       */
      public boolean hasDirectAction() {
        return instance.hasDirectAction();
      }
      /**
       * <pre>
       * Optionally map this script to a direct action.
       * </pre>
       *
       * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
       */
      public org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto getDirectAction() {
        return instance.getDirectAction();
      }
      /**
       * <pre>
       * Optionally map this script to a direct action.
       * </pre>
       *
       * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
       */
      public Builder setDirectAction(org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto value) {
        copyOnWrite();
        instance.setDirectAction(value);
        return this;
        }
      /**
       * <pre>
       * Optionally map this script to a direct action.
       * </pre>
       *
       * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
       */
      public Builder setDirectAction(
          org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto.Builder builderForValue) {
        copyOnWrite();
        instance.setDirectAction(builderForValue);
        return this;
      }
      /**
       * <pre>
       * Optionally map this script to a direct action.
       * </pre>
       *
       * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
       */
      public Builder mergeDirectAction(org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto value) {
        copyOnWrite();
        instance.mergeDirectAction(value);
        return this;
      }
      /**
       * <pre>
       * Optionally map this script to a direct action.
       * </pre>
       *
       * <code>optional .autofill_assistant.DirectActionProto direct_action = 13;</code>
       */
      public Builder clearDirectAction() {  copyOnWrite();
        instance.clearDirectAction();
        return this;
      }

      /**
       * <pre>
       * When set to true this script can be run in 'autostart mode'.
       * </pre>
       *
       * <code>optional bool autostart = 8;</code>
       */
      public boolean hasAutostart() {
        return instance.hasAutostart();
      }
      /**
       * <pre>
       * When set to true this script can be run in 'autostart mode'.
       * </pre>
       *
       * <code>optional bool autostart = 8;</code>
       */
      public boolean getAutostart() {
        return instance.getAutostart();
      }
      /**
       * <pre>
       * When set to true this script can be run in 'autostart mode'.
       * </pre>
       *
       * <code>optional bool autostart = 8;</code>
       */
      public Builder setAutostart(boolean value) {
        copyOnWrite();
        instance.setAutostart(value);
        return this;
      }
      /**
       * <pre>
       * When set to true this script can be run in 'autostart mode'.
       * </pre>
       *
       * <code>optional bool autostart = 8;</code>
       */
      public Builder clearAutostart() {
        copyOnWrite();
        instance.clearAutostart();
        return this;
      }

      /**
       * <pre>
       * When set to true this script will be run from WaitForDom actions with
       * allow_interrupt=true.
       * </pre>
       *
       * <code>optional bool interrupt = 9;</code>
       */
      public boolean hasInterrupt() {
        return instance.hasInterrupt();
      }
      /**
       * <pre>
       * When set to true this script will be run from WaitForDom actions with
       * allow_interrupt=true.
       * </pre>
       *
       * <code>optional bool interrupt = 9;</code>
       */
      public boolean getInterrupt() {
        return instance.getInterrupt();
      }
      /**
       * <pre>
       * When set to true this script will be run from WaitForDom actions with
       * allow_interrupt=true.
       * </pre>
       *
       * <code>optional bool interrupt = 9;</code>
       */
      public Builder setInterrupt(boolean value) {
        copyOnWrite();
        instance.setInterrupt(value);
        return this;
      }
      /**
       * <pre>
       * When set to true this script will be run from WaitForDom actions with
       * allow_interrupt=true.
       * </pre>
       *
       * <code>optional bool interrupt = 9;</code>
       */
      public Builder clearInterrupt() {
        copyOnWrite();
        instance.clearInterrupt();
        return this;
      }

      /**
       * <pre>
       * Message to show once the script has been started. This is shown while
       * loading the actions.
       * </pre>
       *
       * <code>optional string start_message = 14;</code>
       */
      public boolean hasStartMessage() {
        return instance.hasStartMessage();
      }
      /**
       * <pre>
       * Message to show once the script has been started. This is shown while
       * loading the actions.
       * </pre>
       *
       * <code>optional string start_message = 14;</code>
       */
      public java.lang.String getStartMessage() {
        return instance.getStartMessage();
      }
      /**
       * <pre>
       * Message to show once the script has been started. This is shown while
       * loading the actions.
       * </pre>
       *
       * <code>optional string start_message = 14;</code>
       */
      public com.google.protobuf.ByteString
          getStartMessageBytes() {
        return instance.getStartMessageBytes();
      }
      /**
       * <pre>
       * Message to show once the script has been started. This is shown while
       * loading the actions.
       * </pre>
       *
       * <code>optional string start_message = 14;</code>
       */
      public Builder setStartMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setStartMessage(value);
        return this;
      }
      /**
       * <pre>
       * Message to show once the script has been started. This is shown while
       * loading the actions.
       * </pre>
       *
       * <code>optional string start_message = 14;</code>
       */
      public Builder clearStartMessage() {
        copyOnWrite();
        instance.clearStartMessage();
        return this;
      }
      /**
       * <pre>
       * Message to show once the script has been started. This is shown while
       * loading the actions.
       * </pre>
       *
       * <code>optional string start_message = 14;</code>
       */
      public Builder setStartMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStartMessageBytes(value);
        return this;
      }

      /**
       * <pre>
       * Show the UI if it's not shown yet. Setting this to false is useful for
       * scripts started by direct actions.
       * </pre>
       *
       * <code>optional bool needs_ui = 15 [default = true];</code>
       */
      public boolean hasNeedsUi() {
        return instance.hasNeedsUi();
      }
      /**
       * <pre>
       * Show the UI if it's not shown yet. Setting this to false is useful for
       * scripts started by direct actions.
       * </pre>
       *
       * <code>optional bool needs_ui = 15 [default = true];</code>
       */
      public boolean getNeedsUi() {
        return instance.getNeedsUi();
      }
      /**
       * <pre>
       * Show the UI if it's not shown yet. Setting this to false is useful for
       * scripts started by direct actions.
       * </pre>
       *
       * <code>optional bool needs_ui = 15 [default = true];</code>
       */
      public Builder setNeedsUi(boolean value) {
        copyOnWrite();
        instance.setNeedsUi(value);
        return this;
      }
      /**
       * <pre>
       * Show the UI if it's not shown yet. Setting this to false is useful for
       * scripts started by direct actions.
       * </pre>
       *
       * <code>optional bool needs_ui = 15 [default = true];</code>
       */
      public Builder clearNeedsUi() {
        copyOnWrite();
        instance.clearNeedsUi();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:autofill_assistant.SupportedScriptProto.PresentationProto)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto other = (org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto) arg1;
          precondition_ = visitor.visitMessage(precondition_, other.precondition_);
          initialPrompt_ = visitor.visitString(
              hasInitialPrompt(), initialPrompt_,
              other.hasInitialPrompt(), other.initialPrompt_);
          priority_ = visitor.visitInt(
              hasPriority(), priority_,
              other.hasPriority(), other.priority_);
          chip_ = visitor.visitMessage(chip_, other.chip_);
          directAction_ = visitor.visitMessage(directAction_, other.directAction_);
          autostart_ = visitor.visitBoolean(
              hasAutostart(), autostart_,
              other.hasAutostart(), other.autostart_);
          interrupt_ = visitor.visitBoolean(
              hasInterrupt(), interrupt_,
              other.hasInterrupt(), other.interrupt_);
          startMessage_ = visitor.visitString(
              hasStartMessage(), startMessage_,
              other.hasStartMessage(), other.startMessage_);
          needsUi_ = visitor.visitBoolean(
              hasNeedsUi(), needsUi_,
              other.hasNeedsUi(), other.needsUi_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 26: {
                  org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    subBuilder = precondition_.toBuilder();
                  }
                  precondition_ = input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.ScriptPreconditionProto.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(precondition_);
                    precondition_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000001;
                  break;
                }
                case 34: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  initialPrompt_ = s;
                  break;
                }
                case 40: {
                  bitField0_ |= 0x00000004;
                  priority_ = input.readInt32();
                  break;
                }
                case 64: {
                  bitField0_ |= 0x00000020;
                  autostart_ = input.readBool();
                  break;
                }
                case 72: {
                  bitField0_ |= 0x00000040;
                  interrupt_ = input.readBool();
                  break;
                }
                case 98: {
                  org.chromium.chrome.browser.autofill_assistant.proto.ChipProto.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    subBuilder = chip_.toBuilder();
                  }
                  chip_ = input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.ChipProto.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(chip_);
                    chip_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000008;
                  break;
                }
                case 106: {
                  org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    subBuilder = directAction_.toBuilder();
                  }
                  directAction_ = input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.DirectActionProto.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(directAction_);
                    directAction_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000010;
                  break;
                }
                case 114: {
                  String s = input.readString();
                  bitField0_ |= 0x00000080;
                  startMessage_ = s;
                  break;
                }
                case 120: {
                  bitField0_ |= 0x00000100;
                  needsUi_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:autofill_assistant.SupportedScriptProto.PresentationProto)
    private static final org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PresentationProto();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PresentationProto> PARSER;

    public static com.google.protobuf.Parser<PresentationProto> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  private int bitField0_;
  public static final int PATH_FIELD_NUMBER = 1;
  private java.lang.String path_;
  /**
   * <pre>
   * This is the internal name of the script.
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  public boolean hasPath() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * This is the internal name of the script.
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  public java.lang.String getPath() {
    return path_;
  }
  /**
   * <pre>
   * This is the internal name of the script.
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(path_);
  }
  /**
   * <pre>
   * This is the internal name of the script.
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  private void setPath(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    path_ = value;
  }
  /**
   * <pre>
   * This is the internal name of the script.
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  private void clearPath() {
    bitField0_ = (bitField0_ & ~0x00000001);
    path_ = getDefaultInstance().getPath();
  }
  /**
   * <pre>
   * This is the internal name of the script.
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  private void setPathBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    path_ = value.toStringUtf8();
  }

  public static final int PRESENTATION_FIELD_NUMBER = 2;
  private org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto presentation_;
  /**
   * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
   */
  public boolean hasPresentation() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
   */
  public org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto getPresentation() {
    return presentation_ == null ? org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.getDefaultInstance() : presentation_;
  }
  /**
   * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
   */
  private void setPresentation(org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto value) {
    if (value == null) {
      throw new NullPointerException();
    }
    presentation_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
   */
  private void setPresentation(
      org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.Builder builderForValue) {
    presentation_ = builderForValue.build();
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
   */
  private void mergePresentation(org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto value) {
    if (presentation_ != null &&
        presentation_ != org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.getDefaultInstance()) {
      presentation_ =
        org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.newBuilder(presentation_).mergeFrom(value).buildPartial();
    } else {
      presentation_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
   */
  private void clearPresentation() {  presentation_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getPath());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, getPresentation());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getPath());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPresentation());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Supported script.
   * </pre>
   *
   * Protobuf type {@code autofill_assistant.SupportedScriptProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto, Builder> implements
      // @@protoc_insertion_point(builder_implements:autofill_assistant.SupportedScriptProto)
      org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProtoOrBuilder {
    // Construct using org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * This is the internal name of the script.
     * </pre>
     *
     * <code>optional string path = 1;</code>
     */
    public boolean hasPath() {
      return instance.hasPath();
    }
    /**
     * <pre>
     * This is the internal name of the script.
     * </pre>
     *
     * <code>optional string path = 1;</code>
     */
    public java.lang.String getPath() {
      return instance.getPath();
    }
    /**
     * <pre>
     * This is the internal name of the script.
     * </pre>
     *
     * <code>optional string path = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      return instance.getPathBytes();
    }
    /**
     * <pre>
     * This is the internal name of the script.
     * </pre>
     *
     * <code>optional string path = 1;</code>
     */
    public Builder setPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setPath(value);
      return this;
    }
    /**
     * <pre>
     * This is the internal name of the script.
     * </pre>
     *
     * <code>optional string path = 1;</code>
     */
    public Builder clearPath() {
      copyOnWrite();
      instance.clearPath();
      return this;
    }
    /**
     * <pre>
     * This is the internal name of the script.
     * </pre>
     *
     * <code>optional string path = 1;</code>
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPathBytes(value);
      return this;
    }

    /**
     * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
     */
    public boolean hasPresentation() {
      return instance.hasPresentation();
    }
    /**
     * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
     */
    public org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto getPresentation() {
      return instance.getPresentation();
    }
    /**
     * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
     */
    public Builder setPresentation(org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto value) {
      copyOnWrite();
      instance.setPresentation(value);
      return this;
      }
    /**
     * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
     */
    public Builder setPresentation(
        org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.Builder builderForValue) {
      copyOnWrite();
      instance.setPresentation(builderForValue);
      return this;
    }
    /**
     * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
     */
    public Builder mergePresentation(org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto value) {
      copyOnWrite();
      instance.mergePresentation(value);
      return this;
    }
    /**
     * <code>optional .autofill_assistant.SupportedScriptProto.PresentationProto presentation = 2;</code>
     */
    public Builder clearPresentation() {  copyOnWrite();
      instance.clearPresentation();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:autofill_assistant.SupportedScriptProto)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto other = (org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto) arg1;
        path_ = visitor.visitString(
            hasPath(), path_,
            other.hasPath(), other.path_);
        presentation_ = visitor.visitMessage(presentation_, other.presentation_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                path_ = s;
                break;
              }
              case 18: {
                org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = presentation_.toBuilder();
                }
                presentation_ = input.readMessage(org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.PresentationProto.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(presentation_);
                  presentation_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:autofill_assistant.SupportedScriptProto)
  private static final org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SupportedScriptProto();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.chrome.browser.autofill_assistant.proto.SupportedScriptProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SupportedScriptProto> PARSER;

  public static com.google.protobuf.Parser<SupportedScriptProto> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

