// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sharing_message.proto

package org.chromium.components.sync.protocol;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chrome_browser_sharing.ResponseMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .chrome_browser_sharing.SmsFetchResponse sms_fetch_response = 1;</code>
   */
  org.chromium.components.sync.protocol.SmsFetchResponse getSmsFetchResponse();

  /**
   * <code>optional .chrome_browser_sharing.SignallingMessage signalling_message_response = 2;</code>
   */
  org.chromium.components.sync.protocol.SignallingMessage getSignallingMessageResponse();

  public org.chromium.components.sync.protocol.ResponseMessage.PayloadCase getPayloadCase();
}
