// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sharing_shared_clipboard_message.proto

package org.chromium.components.sync.protocol;

public final class SharingSharedClipboardMessage {
  private SharingSharedClipboardMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
